variable "aws_profile" {
  description = "Use this attribute to override the autogenerated profile name."
}

variable "aws_region" {
  description = "AWS region to run the Terraform script."
}

variable "common_tags" {
  type        = map(string)
  description = "Common tags that all resources should have."
  default     = { project = "vogt4nick.com" }
}
